#!/bin/bash
# Script that will build and install Python, TeXLive, and texcaller
# ~/app-root/data directory as needed. Python and TeXLive are downloaded
# and installed if they are not already present. The texcaller module
# is always rebuilt from the source code version present in the
# application's git repository. This script is run every time the app is
# built (i.e., every time the repository is pushed to OpenShift) to ensure
# that all dependencies are properly installed

# Script settings
PythonVersion="2.7.5" # If you change this version, please also update the
		      # Python version numbers in
                      # repo/texcaller/python/Makefile, where repo is your
                      # git repository directory

# Python installer
if [ -e $OPENSHIFT_DATA_DIR/Python/bin/python ]; then
  echo "Python interpreter already installed"
else
  echo "Building Python interpreter" 
  cd $OPENSHIFT_DATA_DIR
  wget http://www.python.org/ftp/python/$PythonVersion/Python-$PythonVersion.tgz
  tar xvfz Python-$PythonVersion.tgz
  cd Python-$PythonVersion
  
  ./configure --enable-shared --prefix=$OPENSHIFT_DATA_DIR/Python
  make
  echo "Installing Python interpreter"
  make install
  cd ..
  mkdir lib
  cd Python-$PythonVersion
  cp libpython2.7.so.1.0 ../lib
  cd ..
  echo "Cleaning up Python installation file"
  rm Python-$PythonVersion.tgz
  echo "Creating Python $PythonVersion virtual environment in the folder "$OPENSHIFT_DATA_DIR"virtenv"
  virtualenv -p ./Python/bin/python --no-site-packages ./virtenv
  echo "Installing additional Python modules using pip"
  source ./virtenv/bin/activate
  pip install tornado
  pip install futures # Add more modules here as needed
  deactivate
  echo "Finished installing Python interpreter"
fi

# TeXLive installer
if [ -e $OPENSHIFT_DATA_DIR/TeXLive/bin/x86_64-linux/pdflatex ]; then
  echo "TeXLive already installed"
else
  echo "Installing TeXLive" 
  cd $OPENSHIFT_DATA_DIR
  wget http://mirror.ctan.org/systems/texlive/tlnet/install-tl-unx.tar.gz 
  tar xvfz install-tl-unx.tar.gz
  rm install-tl-unx.tar.gz 
  mv install-tl* install-tl # Directory name changes with new (apparently daily) builds of the tarball
  cd install-tl
  cp "$OPENSHIFT_REPO_DIR"texlive.profile .
  sed -i "s|\~\/|$HOME|g" ./texlive.profile
  ./install-tl --profile=./texlive.profile
  echo "Cleaning up TeXLive installation files"
  cd ..
  rm -rf install-tl
  echo "Finished installing TeXLive"
fi

# texcaller builder
echo "Building texcaller" 
cd "$OPENSHIFT_REPO_DIR"texcaller/python
make clean
make
rm -f $OPENSHIFT_DATA_DIR"lib"/_texcaller.so
rm -f $OPENSHIFT_DATA_DIR"lib"/texcaller.py
cp _texcaller.so $OPENSHIFT_DATA_DIR"lib"
cp texcaller.py $OPENSHIFT_DATA_DIR"lib"
cd $OPENSHIFT_DATA_DIR
echo "Finished building texcaller"
