#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_DIY_IP:8080
source "$OPENSHIFT_DATA_DIR"virtenv/bin/activate
nohup python -u $OPENSHIFT_REPO_DIR/diy/app.py |& /usr/bin/logshifter -tag diy &
deactivate
